[package]
name = "parse-sap-odata-demo"
edition = "2021"
version = "0.1.7"
authors = ["Chris Whealy <chris@lighthouse.no>"]
description = "Minimal demo app that consumes the SAP OData service GWSAMPLE_BASIC"
keywords = ["odata", "sap", "parser", "opendata", "gwsample_basic"]
repository = "https://github.com/lighthouse-no/parse-sap-odata-demo"
license = "MIT"

[build-dependencies]
# parse-sap-odata = { version = "1.2", features = ["parser"]}
parse-sap-odata = { path = "../parse-sap-odata", features = ["parser"]}

[dependencies]
actix-web = "4.3"
actix-rt = "2.8"
base64 = "0.21"
chrono = { version = "0.4", features = ["serde"]}
env_logger = "0.10"
log = "0.4"
quick-xml = { version = "0.30", features = ["serialize"] }
regex = "1.9"
reqwest = { version = "0.11", features = ["json"]}
# parse-sap-atom-feed = "0.2"
parse-sap-atom-feed = { path = "../parse-sap-atom-feed" }
rust_decimal = { version = "1.30", features = ["serde-with-str"]}
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tinytemplate = "1.2"
uuid = { version = "1.4", features = ["serde"]}
url = "2.4"
